
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "ImageStoreTurboModule.h"

using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_ImageStoreTurboModule_getConstants(jsi::Runtime& rt, react::TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "getConstants", args, count);
}

static jsi::Value __hostFunction_ImageStoreTurboModule_getBase64ForTag(jsi::Runtime& rt, react::TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "getBase64ForTag", args, count);
}

static jsi::Value __hostFunction_ImageStoreTurboModule_hasImageForTag(jsi::Runtime& rt, react::TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "hasImageForTag", args, count);
}

static jsi::Value __hostFunction_ImageStoreTurboModule_removeImageForTag(jsi::Runtime& rt, react::TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "removeImageForTag", args, count);
}

static jsi::Value __hostFunction_ImageStoreTurboModule_addImageFromBase64(jsi::Runtime& rt, react::TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "addImageFromBase64", args, count);
}

ImageStoreTurboModule::ImageStoreTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
  : ArkTSTurboModule(ctx, name) {
  methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_ImageStoreTurboModule_getConstants};
  methodMap_["getBase64ForTag"] = MethodMetadata {3, __hostFunction_ImageStoreTurboModule_getBase64ForTag};
  methodMap_["hasImageForTag"] = MethodMetadata {2, __hostFunction_ImageStoreTurboModule_hasImageForTag};
  methodMap_["removeImageForTag"] = MethodMetadata {1, __hostFunction_ImageStoreTurboModule_removeImageForTag};
  methodMap_["addImageFromBase64"] = MethodMetadata {3, __hostFunction_ImageStoreTurboModule_addImageFromBase64};
}
